export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_USER_INFO = "LOGIN_USER_INFO";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const PRODUCT_TOTAL = "PRODUCT_TOTAL";
export const PENDING_PRODUCT = "PENDING_PRODUCT";
export const COMPANY_LIST = "COMPANY_LIST";
















